import com.sapher.youtubedl.YoutubeDL;
import com.sapher.youtubedl.YoutubeDLException;
import com.sapher.youtubedl.YoutubeDLRequest;
import com.sapher.youtubedl.YoutubeDLResponse;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;

public class SubtitleProcessor {

    /*
    Caption: Autogenerated by Youtube. Might not be precise.
    Subtitle: Might be more precise and more prioritized
     */

    static String prefix = "https://www.youtube.com/watch?v=";
    public boolean idCapt = false;
    public boolean idSubs = false;
    public boolean enCapt = false;
    public boolean enSubs = false;
    private String videoId;
    private Path dir;

    public SubtitleProcessor(String videoId, Path dir) {
        this.videoId = videoId;
        this.dir = dir;
    }

    // TODO: SRT parser, Generator, Text Exporter

    public void checkSubs() throws IOException, YoutubeDLException {

        YoutubeDLRequest yt = new YoutubeDLRequest(prefix + videoId);
        yt.setOption("list-subs");
        YoutubeDLResponse res = YoutubeDL.execute(yt);

        BufferedReader reader = new BufferedReader(new StringReader(res.getOut()));
        String line;
        while ((line = reader.readLine()) != null) {
            if (line.contains("Available automatic captions")) {
                line = reader.readLine();
                while (!(line.contains("Available") || (line.contains("has no")))) {
                    String check = line.substring(0, 2);
                    if (check.equals("id")) {
                        idCapt = true;
                    } else if (check.equals("en")) {
                        enCapt = true;
                    }
                    line = reader.readLine();
                }
            }
            if (line.contains("Available subtitles")) {
                line = reader.readLine();
                while (line != null) {
                    String check = line.substring(0, 2);
                    if (check.equals("id")) {
                        idSubs = true;
                    } else if (check.equals("en")) {
                        enSubs = true;
                    }
                    line = reader.readLine();
                }
            }
        }
    }

    /**
     * Get the subtitle/closed-captions from the video.
     *
     * lang     type    description
     * true     true    Indonesian, subtitle
     * true     false   Indonesian, closed-caption
     * false    true    English, subtitle
     * false    false   English, closed-caption
     *
     * @param lang choose the language of the captions
     * @param type choose the type of the captions
     * @return void
     */
    public void downSub(boolean lang, boolean type) throws YoutubeDLException {
        YoutubeDLRequest yt = new YoutubeDLRequest(prefix + videoId);
        yt.setOption("sub-format", "vtt");
        yt.setOption("skip-download");

        // Boolean doesn't work? :/
        if (lang && type && idSubs) {
            yt.setOption("write-sub");
            yt.setOption("sub-lang", "id");
            yt.setOption("output", Paths.get(dir.toString(), "sub.%(id)s.%(ext)s").toString());
        } else if (lang && !type && idCapt) {
            yt.setOption("write-auto-sub");
            yt.setOption("sub-lang", "id");
            yt.setOption("output", Paths.get(dir.toString(), "auto.%(id)s.%(ext)s").toString());
        } else if (!lang && type && enSubs) {
            yt.setOption("write-sub");
            yt.setOption("sub-lang", "en");
            yt.setOption("output", Paths.get(dir.toString(), "sub.%(id)s.%(ext)s").toString());
        } else if (!lang && !type && enCapt) {
            yt.setOption("write-auto-sub");
            yt.setOption("sub-lang", "en");
            yt.setOption("output", Paths.get(dir.toString(), "auto.%(id)s.%(ext)s").toString());
        }
        YoutubeDL.execute(yt);
    }

    public void downAllSub() { // This is veeeeery slow
        try {
            if (idSubs) {
                downSub(true, true);
            }
            if (idCapt) {
                downSub(true, false);
            }
            if (enSubs) {
                downSub(false, true);
            }
            if (enCapt) {
                downSub(false, false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public ArrayList<LinkedText> parseFile(boolean type, boolean lang) {
        String typeString = (type) ? "sub" : "auto";
        String langString = (lang) ? "id" : "en";
        String fileName = String.format("%s.%s.%s.vtt", typeString, videoId, langString);
        File file = new File(dir.toFile(), fileName);
        System.out.println(file.toString());
        return new ParseSubtitle(file, videoId).getTranscript(); // The array is for storage
        // If the user changed the language setting, the previous language is still stored
        // And the new language is processed on-the-fly
    }

    public String getVideoId() {
        return videoId;
    }
}
